#!/usr/bin/env bash
# Generates Sources/Fyrestore/Secrets.swift from environment variables.
# Run this once per machine after cloning the repo (or whenever your OAuth
# credentials change). The generated file is gitignored.
#
# Usage:
#   export FYRESTORE_CLIENT_ID="…apps.googleusercontent.com"
#   export FYRESTORE_CLIENT_SECRET="GOCSPX-…"
#   ./scripts/setup-secrets.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TARGET="$REPO_ROOT/Sources/Fyrestore/Secrets.swift"

if [[ -z "${FYRESTORE_CLIENT_ID:-}" || -z "${FYRESTORE_CLIENT_SECRET:-}" ]]; then
  cat <<EOF >&2
✗ Missing FYRESTORE_CLIENT_ID and/or FYRESTORE_CLIENT_SECRET environment variables.

  Set them and re-run:
    export FYRESTORE_CLIENT_ID="…apps.googleusercontent.com"
    export FYRESTORE_CLIENT_SECRET="GOCSPX-…"
    ./scripts/setup-secrets.sh

  See README → "For maintainers / forking the repo" to register an OAuth client.
EOF
  exit 1
fi

cat > "$TARGET" <<EOF
// Generated by scripts/setup-secrets.sh — do not commit. Gitignored.
import Foundation

enum Secrets {
    static let clientID = "$FYRESTORE_CLIENT_ID"
    static let clientSecret = "$FYRESTORE_CLIENT_SECRET"
}
EOF

echo "✓ Wrote $TARGET"
